title:              Spam Catch Sri Lanka
email:              spamcatchlk@gmail.com
description:        We catch spams, that running on Sri Lanka
author:             SpamCatchLK
baseurl:            "/"
url:                "https://spamcatchlk.github.io"

# Social Profiles
twitter_username:   SpamCatchLK
github_username:    SpamCatchLK
facebook_username:  SpamCatchLK
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
